#pragma once
// epub_strings.h contains the epub metadata to be written out to file

static const char* bkpstring = "wn-epuber (0.1)";
static const char* epubstylesheetcss = 
	".calibre {\n"
	"  display: block;\n"
	"  font-size: 1em;\n"
	"  padding-left: 0;\n"
	"  padding-right: 0;\n"
	"  margin: 0 5pt;\n"
	"}\n"
	"\n"
	".calibre1 {\n"
	"  display: block;\n"
	"  margin: 1em 0;\n"
	"}\n"
	"\n"
	".scenebreak {\n"
	"  display: block;\n"
	"  page-break-before: avoid;\n"
	"  text-align: center;\n"
	"  text-indent: 0%;\n"
	"  margin: 1em 0;\n"
	"}\n"
	"\n"
	".softbreak {\n"
	"  display: block;\n"
	"  page-break-before: avoid;\n"
	"  text-align: center;\n"
	"  margin: 0.5em 0 1em;\n"
	"}\n"
	"\n"
	"@page {\n"
	"  margin-bottom: 5pt;\n"
	"  margin-top: 5pt;\n"
	"}\n"
	"";
static const char* epubcontainerxml =
	"<?xml version=\"1.0\"?>\n"
	"<container version=\"1.0\" xmlns=\"urn:oasis:names:tc:opendocument:xmlns:container\">\n"
	"   <rootfiles>\n"
	"      <rootfile full-path=\"content.opf\" media-type=\"application/oebps-package+xml\"/>\n"
	"   </rootfiles>\n"
	"</container>\n"
	"";
static const char* epubcontentopf = 
	"<?xml version='1.0' encoding='utf-8'?>\n"
	"<package xmlns=\"http://www.idpf.org/2007/opf\" version=\"2.0\" unique-identifier=\"uuid_id\">\n"
	"  <metadata xmlns:opf=\"http://www.idpf.org/2007/opf\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
	"    <dc:title></dc:title>\n"
	"    <dc:language></dc:language>\n"
	"    <dc:creator opf:file-as=\"\" opf:role=\"aut\"></dc:creator>\n"
	"    <dc:identifier id=\"uuid_id\" opf:scheme=\"uuid\"></dc:identifier>\n"
	"    <dc:contributor opf:role=\"bkp\"></dc:contributor>\n"
	"    <dc:date></dc:date>\n"
	"    <meta name=\"cover\" content=\"cover\"/>\n"
	"  </metadata>\n"
	"  <manifest>\n"
	"    <item id=\"cover\" href=\"cover.jpg\" media-type=\"image/jpeg\"/>\n"
	"    <item id=\"titlepage\" href=\"titlepage.xhtml\" media-type=\"application/xhtml+xml\"/>\n"
	"    <item id=\"css\" href=\"stylesheet.css\" media-type=\"text/css\"/>\n"
	"    <item id=\"ncx\" href=\"toc.ncx\" media-type=\"application/x-dtbncx+xml\"/>\n"
	"  </manifest>\n"
	"  <spine toc=\"ncx\">\n"
	"    <itemref idref=\"titlepage\"/>\n"
	"  </spine>\n"
	"  <guide>\n"
	"    <reference type=\"cover\" href=\"titlepage.xhtml\" title=\"Cover\"/>\n"
	"  </guide>\n"
	"</package>\n"
	"";
static const char* epubtocncx = 
	"<?xml version='1.0' encoding='utf-8'?>\n"
	"<ncx xmlns=\"http://www.daisy.org/z3986/2005/ncx/\" version=\"2005-1\" xml:lang=\"eng\">\n"
	"  <head>\n"
	"    <meta name=\"dtb:uid\" content=\"\"/>\n"
	"    <meta name=\"dtb:depth\" content=\"2\"/>\n"
	"    <meta name=\"dtb:generator\" content=\"\"/>\n"
	"    <meta name=\"dtb:totalPageCount\" content=\"0\"/>\n"
	"    <meta name=\"dtb:maxPageNumber\" content=\"0\"/>\n"
	"  </head>\n"
	"  <docTitle>\n"
	"    <text></text>\n"
	"  </docTitle>\n"
	"  <navMap>\n"
	"    <navPoint id=\"c2hvdXRvdXQgdG8gYWNpZUw\" playOrder=\"1\">\n"
	"      <navLabel>\n"
	"        <text>Start</text>\n"
	"      </navLabel>\n"
	"      <content src=\"titlepage.xhtml\"/>\n"
	"    </navPoint>\n\n"
	"  </navMap>\n"
	"</ncx>\n"
	"";
static const char* epubtitlepagexhtml =
	"<?xml version='1.0' encoding='utf-8'?>\n"
	"<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\">\n"
	"    <head>\n"
	"        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\n"
	"        <title>Cover</title>\n"
	"        <style type=\"text/css\" title=\"override_css\">\n"
	"            @page {padding: 0pt; margin:0pt}\n"
	"            body { text-align: center; padding:0pt; margin: 0pt; }\n"
	"        </style>\n"
	"    </head>\n"
	"    <body>\n"
	"        <div>\n"
	"            <svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" version=\"1.1\" width=\"100%\" height=\"100%\" viewBox=\"0 0  \" preserveAspectRatio=\"none\">\n"
	"                <image width=\"\" height=\"\" xlink:href=\"cover.jpg\"/>\n"
	"            </svg>\n"
	"        </div>\n"
	"    </body>\n"
	"</html>\n"
	"";
static const char* epubnavpoint =
	"    <navPoint id=\"\" playOrder=\"\">\n"
	"      <navLabel>\n"
	"        <text></text>\n"
	"      </navLabel>\n"
	"      <content src=\"\"/>\n"
	"    </navPoint>\n"
	"";
